overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            auto_discover: true
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: ~
    errors_handler:
        enabled: true
        internal_error_message: "An internal error occurred."
        rethrow_internal_exceptions: false
        debug: false
        map_exceptions_to_parent: true
        exceptions:
            warnings:
                - App\Domain\Exception\InvalidStatusTransitionException
                - App\Domain\Exception\TaskNotFoundException
                - App\Domain\Exception\TaskPersistenceException
                - App\Domain\Exception\TaskValidationException
                - App\Domain\Exception\UserNotFoundException
                - App\Domain\Exception\InvalidCredentialsException
                - App\Domain\Exception\InvalidRefreshTokenException