Mutation:
    type: object
    config:
        fields:
            login:
                type: "AuthPayload!"
                args:
                    input:
                        type: "LoginInput!"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\UserMutationResolver').login(args['input'])"
            refreshToken:
                type: "AuthPayload!"
                args:
                    input:
                        type: "RefreshTokenInput!"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\UserMutationResolver').refreshToken(args['input'])"
            syncUsersFromApi:
                type: "ImportUsersResult!"
                access: "@=isAuthenticated()"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\UserMutationResolver').syncUsersFromApi()"
            createTask:
                type: "Task!"
                access: "@=isAuthenticated()"
                args:
                    input:
                        type: "CreateTaskInput!"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\TaskMutationResolver').createTask(args['input'])"
            updateTask:
                type: "Task!"
                access: "@=isAuthenticated()"
                args:
                    id:
                        type: "Int!"
                    input:
                        type: "UpdateTaskInput!"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\TaskMutationResolver').updateTask(args['id'], args['input'])"
            changeTaskStatus:
                type: "Task!"
                access: "@=isAuthenticated()"
                args:
                    id:
                        type: "Int!"
                    status:
                        type: "TaskStatus!"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\TaskMutationResolver').changeTaskStatus(args['id'], args['status'])"
            deleteTask:
                type: "Boolean!"
                access: "@=isAuthenticated()"
                args:
                    id:
                        type: "Int!"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\TaskMutationResolver').deleteTask(args['id'])"
