Query:
    type: object
    config:
        fields:
            task:
                type: "Task"
                args:
                    id:
                        type: "Int!"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\TaskQueryResolver').findById(args['id'])"
            tasks:
                type: "[Task!]!"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\TaskQueryResolver').findAll()"
            tasksByUser:
                type: "[Task!]!"
                args:
                    userId:
                        type: "Int!"
                resolve: "@=service('App\\\\UI\\\\GraphQL\\\\Resolver\\\\TaskQueryResolver').findByUserId(args['userId'])"
