<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260309203000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create task_events table for event sourcing';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE task_events (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            task_id INT NOT NULL,
            event_type VARCHAR(50) NOT NULL,
            payload JSONB NOT NULL,
            user_id INT NOT NULL,
            occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_TASK_EVENTS_TASK_ID ON task_events (task_id)');
        $this->addSql('ALTER TABLE task_events ADD CONSTRAINT FK_TASK_EVENTS_TASK FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task_events ADD CONSTRAINT FK_TASK_EVENTS_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE task_events');
    }
}
