<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260309162707 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE refresh_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(128) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E15F37A13B ON refresh_tokens (token)');
        $this->addSql('CREATE INDEX IDX_9BACE7E1A76ED395 ON refresh_tokens (user_id)');
        $this->addSql('CREATE INDEX idx_refresh_token_expires ON refresh_tokens (expires_at)');
        $this->addSql('ALTER TABLE refresh_tokens ADD CONSTRAINT FK_9BACE7E1A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tasks ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tasks ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE tasks ALTER status DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN tasks.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN tasks.updated_at IS \'\'');
        $this->addSql('ALTER INDEX idx_tasks_assigned_user_id RENAME TO IDX_50586597ADF66B1A');
        $this->addSql('DROP INDEX uniq_8d93d649e7927c74');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE users ALTER email TYPE VARCHAR(180)');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lat DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lng DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lat TYPE NUMERIC(10, 8) USING address_geo_lat::numeric(10,8)');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lng TYPE NUMERIC(11, 8) USING address_geo_lng::numeric(11,8)');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE refresh_tokens DROP CONSTRAINT FK_9BACE7E1A76ED395');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('ALTER TABLE tasks ALTER id SET DEFAULT nextval(\'tasks_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE tasks ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE tasks ALTER status SET DEFAULT \'To Do\'');
        $this->addSql('COMMENT ON COLUMN tasks.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN tasks.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_50586597adf66b1a RENAME TO idx_tasks_assigned_user_id');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER email TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lat DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lng DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lat TYPE VARCHAR(50) USING address_geo_lat::text');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lng TYPE VARCHAR(50) USING address_geo_lng::text');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lat SET DEFAULT NULL');
        $this->addSql('ALTER TABLE users ALTER COLUMN address_geo_lng SET DEFAULT NULL');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE UNIQUE INDEX uniq_8d93d649e7927c74 ON users (email)');
    }
}
